// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace webapplication.Migrations.afspraakDb
{
    [DbContext(typeof(afspraakDbContext))]
    [Migration("20220118121923_afspraak")]
    partial class afspraak
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HulpverlenerModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NaamZorgverlener")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("beschikbareDagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("beschikbareTijden")
                        .HasColumnType("TEXT");

                    b.Property<string>("clientNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("HulpverlenerModel");
                });

            modelBuilder.Entity("afspraakModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BSN")
                        .HasColumnType("TEXT");

                    b.Property<string>("achternaam")
                        .HasColumnType("TEXT");

                    b.Property<string>("emailvanGebruiker")
                        .HasColumnType("TEXT");

                    b.Property<string>("emailvanOuder")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("geboorteDatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("gekozenDatum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("gekozenHulpverlenerid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("gekozenTijd")
                        .HasColumnType("TEXT");

                    b.Property<bool>("jongerDan16")
                        .HasColumnType("INTEGER");

                    b.Property<string>("voornaam")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("gekozenHulpverlenerid");

                    b.ToTable("afspraakModel");
                });

            modelBuilder.Entity("afspraakModel", b =>
                {
                    b.HasOne("HulpverlenerModel", "gekozenHulpverlener")
                        .WithMany()
                        .HasForeignKey("gekozenHulpverlenerid");

                    b.Navigation("gekozenHulpverlener");
                });
#pragma warning restore 612, 618
        }
    }
}
