// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace webapplication.Migrations.AfspraakDb
{
    [DbContext(typeof(AfspraakDbContext))]
    [Migration("20220202215713_InitialChatDb")]
    partial class InitialChatDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HulpverlenerModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NaamZorgverlener")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("beschikbareDagen")
                        .HasColumnType("datetime2");

                    b.Property<string>("beschikbareTijden")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("HulpverlenerModel");
                });

            modelBuilder.Entity("afspraakModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("achternaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailvanGebruiker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailvanOuder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("geboorteDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("gekozenDatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("gekozenHulpverlenerid")
                        .HasColumnType("int");

                    b.Property<string>("gekozenTijd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("jongerDan16")
                        .HasColumnType("bit");

                    b.Property<string>("naamOuder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("gekozenHulpverlenerid");

                    b.ToTable("afspraakModel");
                });

            modelBuilder.Entity("afspraakModel", b =>
                {
                    b.HasOne("HulpverlenerModel", "gekozenHulpverlener")
                        .WithMany()
                        .HasForeignKey("gekozenHulpverlenerid");

                    b.Navigation("gekozenHulpverlener");
                });
#pragma warning restore 612, 618
        }
    }
}
