// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace webapplication.Migrations.AfspraakDb
{
    [DbContext(typeof(AfspraakDbContext))]
    [Migration("20220203122617_fixGebJaarBSN")]
    partial class fixGebJaarBSN
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("afspraakModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BSN")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("achternaam")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("emailvanGebruiker")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("emailvanOuder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("geboorteDatum")
                        .HasColumnType("int");

                    b.Property<DateTime>("gekozenDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("gekozenHulpverlener")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gekozenTijd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naamOuder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("voornaam")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("id");

                    b.ToTable("afspraakModel");
                });
#pragma warning restore 612, 618
        }
    }
}
